export interface TestCase {
  id: string;
  name: string;
  code: string;
  expectedTimeComplexity: string;
  expectedSpaceComplexity: string;
  note?: string;
}

export const TEST_CASES: TestCase[] = [
  {
    id: 'TC001',
    name: 'constant_time',
    code: 'function example(n) {\n  const result = n * 2 + 10;\n  return result;\n}',
    expectedTimeComplexity: 'O(1)',
    expectedSpaceComplexity: 'O(1)',
  },
  {
    id: 'TC002',
    name: 'single_linear_loop',
    code: 'function example(arr) {\n  let sum = 0;\n  for (let i = 0; i < arr.length; i++) {\n    sum += arr[i];\n  }\n  return sum;\n}',
    expectedTimeComplexity: 'O(n)',
    expectedSpaceComplexity: 'O(1)',
  },
  {
    id: 'TC003',
    name: 'linear_loop_with_constant_inner_loop',
    code: 'function example(arr) {\n  let count = 0;\n  for (let i = 0; i < arr.length; i++) {\n    for (let j = 0; j < 10; j++) {\n      count++;\n    }\n  }\n  return count;\n}',
    expectedTimeComplexity: 'O(n)',
    expectedSpaceComplexity: 'O(1)',
  },
  {
    id: 'TC004',
    name: 'quadratic_nested_loops',
    code: 'function example(arr) {\n  let count = 0;\n  for (let i = 0; i < arr.length; i++) {\n    for (let j = 0; j < arr.length; j++) {\n      count++;\n    }\n  }\n  return count;\n}',
    expectedTimeComplexity: 'O(n^2)',
    expectedSpaceComplexity: 'O(1)',
  },
  {
    id: 'TC005',
    name: 'triangular_nested_loop',
    code: 'function example(arr) {\n  let count = 0;\n  for (let i = 0; i < arr.length; i++) {\n    for (let j = i; j < arr.length; j++) {\n      count++;\n    }\n  }\n  return count;\n}',
    expectedTimeComplexity: 'O(n^2)',
    expectedSpaceComplexity: 'O(1)',
  },
  {
    id: 'TC006',
    name: 'cubic_nested_loops',
    code: 'function example(n) {\n  let count = 0;\n  for (let i = 0; i < n; i++) {\n    for (let j = 0; j < n; j++) {\n      for (let k = 0; k < n; k++) {\n        count++;\n      }\n    }\n  }\n  return count;\n}',
    expectedTimeComplexity: 'O(n^3)',
    expectedSpaceComplexity: 'O(1)',
  },
  {
    id: 'TC007',
    name: 'logarithmic_loop',
    code: 'function example(n) {\n  let count = 0;\n  for (let i = 1; i < n; i *= 2) {\n    count++;\n  }\n  return count;\n}',
    expectedTimeComplexity: 'O(log n)',
    expectedSpaceComplexity: 'O(1)',
  },
  {
    id: 'TC008',
    name: 'logarithmic_while_loop',
    code: 'function example(n) {\n  let count = 0;\n  while (n > 1) {\n    n = Math.floor(n / 2);\n    count++;\n  }\n  return count;\n}',
    expectedTimeComplexity: 'O(log n)',
    expectedSpaceComplexity: 'O(1)',
  },
  {
    id: 'TC009',
    name: 'linear_logarithmic',
    code: 'function example(n) {\n  let count = 0;\n  for (let i = 0; i < n; i++) {\n    for (let j = 1; j < n; j *= 2) {\n      count++;\n    }\n  }\n  return count;\n}',
    expectedTimeComplexity: 'O(n log n)',
    expectedSpaceComplexity: 'O(1)',
  },
  {
    id: 'TC010',
    name: 'two_separate_linear_loops',
    code: 'function example(arr) {\n  let sum = 0;\n  for (let i = 0; i < arr.length; i++) {\n    sum += arr[i];\n  }\n  for (let i = 0; i < arr.length; i++) {\n    sum += arr[i] * 2;\n  }\n  return sum;\n}',
    expectedTimeComplexity: 'O(n)',
    expectedSpaceComplexity: 'O(1)',
  },
  {
    id: 'TC011',
    name: 'linear_plus_quadratic',
    code: 'function example(arr) {\n  let count = 0;\n  for (let i = 0; i < arr.length; i++) {\n    count++;\n  }\n  for (let i = 0; i < arr.length; i++) {\n    for (let j = 0; j < arr.length; j++) {\n      count++;\n    }\n  }\n  return count;\n}',
    expectedTimeComplexity: 'O(n^2)',
    expectedSpaceComplexity: 'O(1)',
  },
  {
    id: 'TC012',
    name: 'linear_array_creation',
    code: 'function example(arr) {\n  const result = [];\n  for (let i = 0; i < arr.length; i++) {\n    result.push(arr[i] * 2);\n  }\n  return result;\n}',
    expectedTimeComplexity: 'O(n)',
    expectedSpaceComplexity: 'O(n)',
  },
  {
    id: 'TC013',
    name: 'quadratic_matrix_creation',
    code: 'function example(n) {\n  const matrix = [];\n  for (let i = 0; i < n; i++) {\n    const row = [];\n    for (let j = 0; j < n; j++) {\n      row.push(i + j);\n    }\n    matrix.push(row);\n  }\n  return matrix;\n}',
    expectedTimeComplexity: 'O(n^2)',
    expectedSpaceComplexity: 'O(n^2)',
  },
  {
    id: 'TC014',
    name: 'two_pointers',
    code: 'function hasPair(arr, target) {\n  let left = 0;\n  let right = arr.length - 1;\n  while (left < right) {\n    const sum = arr[left] + arr[right];\n    if (sum === target) return true;\n    if (sum < target) left++;\n    else right--;\n  }\n  return false;\n}',
    expectedTimeComplexity: 'O(n)',
    expectedSpaceComplexity: 'O(1)',
  },
  {
    id: 'TC015',
    name: 'sliding_window',
    code: 'function maxSum(arr, k) {\n  let sum = 0;\n  for (let i = 0; i < k; i++) {\n    sum += arr[i];\n  }\n  let max = sum;\n  for (let i = k; i < arr.length; i++) {\n    sum += arr[i] - arr[i - k];\n    max = Math.max(max, sum);\n  }\n  return max;\n}',
    expectedTimeComplexity: 'O(n)',
    expectedSpaceComplexity: 'O(1)',
  },
  {
    id: 'TC016',
    name: 'binary_search_iterative',
    code: 'function binarySearch(arr, target) {\n  let left = 0;\n  let right = arr.length - 1;\n  while (left <= right) {\n    const mid = Math.floor((left + right) / 2);\n    if (arr[mid] === target) return mid;\n    if (arr[mid] < target) left = mid + 1;\n    else right = mid - 1;\n  }\n  return -1;\n}',
    expectedTimeComplexity: 'O(log n)',
    expectedSpaceComplexity: 'O(1)',
  },
  {
    id: 'TC017',
    name: 'binary_search_recursive',
    code: 'function binarySearch(arr, target, left = 0, right = arr.length - 1) {\n  if (left > right) return -1;\n  const mid = Math.floor((left + right) / 2);\n  if (arr[mid] === target) return mid;\n  if (arr[mid] > target) return binarySearch(arr, target, left, mid - 1);\n  return binarySearch(arr, target, mid + 1, right);\n}',
    expectedTimeComplexity: 'O(log n)',
    expectedSpaceComplexity: 'O(log n)',
  },
  {
    id: 'TC018',
    name: 'linear_recursion',
    code: 'function sum(n) {\n  if (n <= 0) return 0;\n  return n + sum(n - 1);\n}',
    expectedTimeComplexity: 'O(n)',
    expectedSpaceComplexity: 'O(n)',
  },
  {
    id: 'TC019',
    name: 'factorial_recursion',
    code: 'function factorial(n) {\n  if (n <= 1) return 1;\n  return n * factorial(n - 1);\n}',
    expectedTimeComplexity: 'O(n)',
    expectedSpaceComplexity: 'O(n)',
  },
  {
    id: 'TC020',
    name: 'fibonacci_naive_recursion',
    code: 'function fibonacci(n) {\n  if (n <= 1) return n;\n  return fibonacci(n - 1) + fibonacci(n - 2);\n}',
    expectedTimeComplexity: 'O(2^n)',
    expectedSpaceComplexity: 'O(n)',
  },
  {
    id: 'TC021',
    name: 'fibonacci_memoized',
    code: 'function fibonacci(n, memo = {}) {\n  if (n <= 1) return n;\n  if (memo[n] !== undefined) return memo[n];\n  memo[n] = fibonacci(n - 1, memo) + fibonacci(n - 2, memo);\n  return memo[n];\n}',
    expectedTimeComplexity: 'O(n)',
    expectedSpaceComplexity: 'O(n)',
  },
  {
    id: 'TC022',
    name: 'merge_sort',
    code: 'function mergeSort(arr) {\n  if (arr.length <= 1) return arr;\n  const mid = Math.floor(arr.length / 2);\n  const left = mergeSort(arr.slice(0, mid));\n  const right = mergeSort(arr.slice(mid));\n  return merge(left, right);\n}\n\nfunction merge(left, right) {\n  const result = [];\n  let i = 0;\n  let j = 0;\n  while (i < left.length && j < right.length) {\n    if (left[i] < right[j]) result.push(left[i++]);\n    else result.push(right[j++]);\n  }\n  return result.concat(left.slice(i), right.slice(j));\n}',
    expectedTimeComplexity: 'O(n log n)',
    expectedSpaceComplexity: 'O(n)',
  },
  {
    id: 'TC023',
    name: 'quick_sort_worst_case',
    code: 'function quickSort(arr) {\n  if (arr.length <= 1) return arr;\n  const pivot = arr[arr.length - 1];\n  const left = [];\n  const right = [];\n  for (let i = 0; i < arr.length - 1; i++) {\n    if (arr[i] < pivot) left.push(arr[i]);\n    else right.push(arr[i]);\n  }\n  return [...quickSort(left), pivot, ...quickSort(right)];\n}',
    expectedTimeComplexity: 'O(n^2) worst case, O(n log n) average',
    expectedSpaceComplexity: 'O(n)',
  },
  {
    id: 'TC024',
    name: 'hash_map_lookup',
    code: 'function twoSum(arr, target) {\n  const map = new Map();\n  for (let i = 0; i < arr.length; i++) {\n    const complement = target - arr[i];\n    if (map.has(complement)) {\n      return [map.get(complement), i];\n    }\n    map.set(arr[i], i);\n  }\n  return [];\n}',
    expectedTimeComplexity: 'O(n) average',
    expectedSpaceComplexity: 'O(n)',
  },
  {
    id: 'TC025',
    name: 'hidden_quadratic_includes',
    code: 'function unique(arr) {\n  const result = [];\n  for (let i = 0; i < arr.length; i++) {\n    if (!result.includes(arr[i])) {\n      result.push(arr[i]);\n    }\n  }\n  return result;\n}',
    expectedTimeComplexity: 'O(n^2)',
    expectedSpaceComplexity: 'O(n)',
  },
  {
    id: 'TC026',
    name: 'set_based_unique',
    code: 'function unique(arr) {\n  return [...new Set(arr)];\n}',
    expectedTimeComplexity: 'O(n) average',
    expectedSpaceComplexity: 'O(n)',
  },
  {
    id: 'TC027',
    name: 'sorting_dominates',
    code: 'function example(arr) {\n  arr.sort((a, b) => a - b);\n  let sum = 0;\n  for (const value of arr) {\n    sum += value;\n  }\n  return sum;\n}',
    expectedTimeComplexity: 'O(n log n)',
    expectedSpaceComplexity: 'O(log n) to O(n), implementation dependent',
  },
  {
    id: 'TC028',
    name: 'dependent_inner_loop',
    code: 'function example(n) {\n  let count = 0;\n  for (let i = 1; i <= n; i++) {\n    for (let j = 1; j <= i; j++) {\n      count++;\n    }\n  }\n  return count;\n}',
    expectedTimeComplexity: 'O(n^2)',
    expectedSpaceComplexity: 'O(1)',
  },
  {
    id: 'TC029',
    name: 'sqrt_loop',
    code: 'function example(n) {\n  let count = 0;\n  for (let i = 1; i * i <= n; i++) {\n    count++;\n  }\n  return count;\n}',
    expectedTimeComplexity: 'O(sqrt(n))',
    expectedSpaceComplexity: 'O(1)',
  },
  {
    id: 'TC030',
    name: 'log_squared',
    code: 'function example(n) {\n  let count = 0;\n  for (let i = 1; i < n; i *= 2) {\n    for (let j = 1; j < n; j *= 2) {\n      count++;\n    }\n  }\n  return count;\n}',
    expectedTimeComplexity: 'O((log n)^2)',
    expectedSpaceComplexity: 'O(1)',
  },
  {
    id: 'TC031',
    name: 'n_sqrt_n',
    code: 'function example(n) {\n  let count = 0;\n  for (let i = 0; i < n; i++) {\n    for (let j = 1; j * j <= n; j++) {\n      count++;\n    }\n  }\n  return count;\n}',
    expectedTimeComplexity: 'O(n sqrt(n))',
    expectedSpaceComplexity: 'O(1)',
  },
  {
    id: 'TC032',
    name: 'two_independent_inputs',
    code: 'function example(arr1, arr2) {\n  let count = 0;\n  for (let i = 0; i < arr1.length; i++) {\n    count++;\n  }\n  for (let j = 0; j < arr2.length; j++) {\n    count++;\n  }\n  return count;\n}',
    expectedTimeComplexity: 'O(n + m)',
    expectedSpaceComplexity: 'O(1)',
  },
  {
    id: 'TC033',
    name: 'two_independent_inputs_nested',
    code: 'function example(arr1, arr2) {\n  let count = 0;\n  for (let i = 0; i < arr1.length; i++) {\n    for (let j = 0; j < arr2.length; j++) {\n      count++;\n    }\n  }\n  return count;\n}',
    expectedTimeComplexity: 'O(n * m)',
    expectedSpaceComplexity: 'O(1)',
  },
  {
    id: 'TC034',
    name: 'early_return_best_case',
    code: 'function contains(arr, target) {\n  for (let i = 0; i < arr.length; i++) {\n    if (arr[i] === target) return true;\n  }\n  return false;\n}',
    expectedTimeComplexity: 'O(n) worst case, O(1) best case',
    expectedSpaceComplexity: 'O(1)',
  },
  {
    id: 'TC035',
    name: 'nested_loop_with_break',
    code: 'function example(arr) {\n  let count = 0;\n  for (let i = 0; i < arr.length; i++) {\n    for (let j = 0; j < arr.length; j++) {\n      count++;\n      if (arr[j] === -1) break;\n    }\n  }\n  return count;\n}',
    expectedTimeComplexity: 'O(n^2) worst case',
    expectedSpaceComplexity: 'O(1)',
  },
  {
    id: 'TC036',
    name: 'linear_recursion_with_array_slice',
    code: 'function sum(arr) {\n  if (arr.length === 0) return 0;\n  return arr[0] + sum(arr.slice(1));\n}',
    expectedTimeComplexity: 'O(n^2)',
    expectedSpaceComplexity: 'O(n^2)',
    note: 'Array slicing creates new arrays at every recursive call.',
  },
  {
    id: 'TC037',
    name: 'recursive_array_generation',
    code: 'function generate(n) {\n  if (n === 0) return [[]];\n  const previous = generate(n - 1);\n  const result = [];\n  for (const item of previous) {\n    result.push([...item, 0]);\n    result.push([...item, 1]);\n  }\n  return result;\n}',
    expectedTimeComplexity: 'O(n * 2^n)',
    expectedSpaceComplexity: 'O(n * 2^n)',
  },
  {
    id: 'TC038',
    name: 'permutation_generation',
    code: 'function permute(arr) {\n  if (arr.length === 0) return [[]];\n  const result = [];\n  for (let i = 0; i < arr.length; i++) {\n    const remaining = [...arr.slice(0, i), ...arr.slice(i + 1)];\n    const permutations = permute(remaining);\n    for (const permutation of permutations) {\n      result.push([arr[i], ...permutation]);\n    }\n  }\n  return result;\n}',
    expectedTimeComplexity: 'O(n * n!)',
    expectedSpaceComplexity: 'O(n * n!)',
  },
  {
    id: 'TC039',
    name: 'power_set',
    code: 'function subsets(arr) {\n  const result = [[]];\n  for (const value of arr) {\n    const size = result.length;\n    for (let i = 0; i < size; i++) {\n      result.push([...result[i], value]);\n    }\n  }\n  return result;\n}',
    expectedTimeComplexity: 'O(n * 2^n)',
    expectedSpaceComplexity: 'O(n * 2^n)',
  },
  {
    id: 'TC040',
    name: 'factorial_growth_recursion',
    code: 'function mystery(n) {\n  if (n <= 1) return 1;\n  let result = 0;\n  for (let i = 0; i < n; i++) {\n    result += mystery(n - 1);\n  }\n  return result;\n}',
    expectedTimeComplexity: 'O(n!)',
    expectedSpaceComplexity: 'O(n)',
  },
  {
    id: 'TC041',
    name: 'nested_recursion_exponential',
    code: 'function mystery(n) {\n  if (n <= 1) return 1;\n  return mystery(n - 1) + mystery(n - 1);\n}',
    expectedTimeComplexity: 'O(2^n)',
    expectedSpaceComplexity: 'O(n)',
  },
  {
    id: 'TC042',
    name: 'tree_traversal',
    code: 'function dfs(node) {\n  if (!node) return;\n  dfs(node.left);\n  dfs(node.right);\n}',
    expectedTimeComplexity: 'O(n)',
    expectedSpaceComplexity: 'O(h)',
  },
  {
    id: 'TC043',
    name: 'bfs_tree_traversal',
    code: 'function bfs(root) {\n  if (!root) return [];\n  const queue = [root];\n  const result = [];\n  while (queue.length > 0) {\n    const node = queue.shift();\n    result.push(node.value);\n    if (node.left) queue.push(node.left);\n    if (node.right) queue.push(node.right);\n  }\n  return result;\n}',
    expectedTimeComplexity:
      'O(n^2) with Array.shift(), O(n) with an optimized queue',
    expectedSpaceComplexity: 'O(n)',
  },
  {
    id: 'TC044',
    name: 'map_filter_reduce_chain',
    code: 'function example(arr) {\n  return arr\n    .filter(x => x % 2 === 0)\n    .map(x => x * 2)\n    .reduce((sum, x) => sum + x, 0);\n}',
    expectedTimeComplexity: 'O(n)',
    expectedSpaceComplexity: 'O(n)',
  },
  {
    id: 'TC045',
    name: 'nested_map',
    code: 'function example(matrix) {\n  return matrix.map(row => row.map(value => value * 2));\n}',
    expectedTimeComplexity: 'O(n * m)',
    expectedSpaceComplexity: 'O(n * m)',
  },
  {
    id: 'TC046',
    name: 'for_each_inside_map',
    code: 'function example(arr) {\n  return arr.map(value => {\n    let sum = 0;\n    arr.forEach(item => {\n      sum += value * item;\n    });\n    return sum;\n  });\n}',
    expectedTimeComplexity: 'O(n^2)',
    expectedSpaceComplexity: 'O(n)',
  },
  {
    id: 'TC047',
    name: 'object_lookup_loop',
    code: 'function example(arr) {\n  const frequency = {};\n  for (const value of arr) {\n    frequency[value] = (frequency[value] || 0) + 1;\n  }\n  return frequency;\n}',
    expectedTimeComplexity: 'O(n) average',
    expectedSpaceComplexity: 'O(n)',
  },
  {
    id: 'TC048',
    name: 'while_with_increment_by_two',
    code: 'function example(n) {\n  let i = 0;\n  while (i < n) {\n    i += 2;\n  }\n}',
    expectedTimeComplexity: 'O(n)',
    expectedSpaceComplexity: 'O(1)',
  },
  {
    id: 'TC049',
    name: 'geometric_nested_decreasing_loop',
    code: 'function example(n) {\n  let count = 0;\n  for (let i = n; i > 0; i = Math.floor(i / 2)) {\n    for (let j = 0; j < i; j++) {\n      count++;\n    }\n  }\n  return count;\n}',
    expectedTimeComplexity: 'O(n)',
    expectedSpaceComplexity: 'O(1)',
  },
  {
    id: 'TC050',
    name: 'double_logarithmic_loop',
    code: 'function example(n) {\n  let count = 0;\n  let i = n;\n  while (i > 1) {\n    i = Math.floor(Math.sqrt(i));\n    count++;\n  }\n  return count;\n}',
    expectedTimeComplexity: 'O(log log n)',
    expectedSpaceComplexity: 'O(1)',
  },
  {
    id: 'TC051',
    name: 'amortized_dynamic_array_push',
    code: 'function example(n) {\n  const arr = [];\n  for (let i = 0; i < n; i++) {\n    arr.push(i);\n  }\n  return arr;\n}',
    expectedTimeComplexity: 'O(n) amortized',
    expectedSpaceComplexity: 'O(n)',
  },
  {
    id: 'TC052',
    name: 'string_search_inside_loop',
    code: 'function example(arr, text) {\n  let count = 0;\n  for (const word of arr) {\n    if (text.includes(word)) {\n      count++;\n    }\n  }\n  return count;\n}',
    expectedTimeComplexity: 'O(n * m) worst case',
    expectedSpaceComplexity: 'O(1)',
  },
  {
    id: 'TC053',
    name: 'object_keys_in_loop',
    code: 'function example(obj) {\n  let count = 0;\n  for (const key of Object.keys(obj)) {\n    count++;\n  }\n  return count;\n}',
    expectedTimeComplexity: 'O(n)',
    expectedSpaceComplexity: 'O(n)',
  },
  {
    id: 'TC054',
    name: 'spread_array_copy',
    code: 'function example(arr) {\n  const copy = [...arr];\n  return copy.reverse();\n}',
    expectedTimeComplexity: 'O(n)',
    expectedSpaceComplexity: 'O(n)',
  },
  {
    id: 'TC055',
    name: 'repeated_array_spread',
    code: 'function example(arr) {\n  let result = [];\n  for (const value of arr) {\n    result = [...result, value];\n  }\n  return result;\n}',
    expectedTimeComplexity: 'O(n^2)',
    expectedSpaceComplexity: 'O(n)',
  },
  {
    id: 'TC056',
    name: 'matrix_transpose',
    code: 'function transpose(matrix) {\n  const rows = matrix.length;\n  const cols = matrix[0].length;\n  const result = [];\n  for (let i = 0; i < cols; i++) {\n    result[i] = [];\n    for (let j = 0; j < rows; j++) {\n      result[i][j] = matrix[j][i];\n    }\n  }\n  return result;\n}',
    expectedTimeComplexity: 'O(n * m)',
    expectedSpaceComplexity: 'O(n * m)',
  },
  {
    id: 'TC057',
    name: 'constant_recursive_calls',
    code: 'function example(n) {\n  if (n <= 1) return 1;\n  return example(n - 1) + example(n - 1) + example(n - 1);\n}',
    expectedTimeComplexity: 'O(3^n)',
    expectedSpaceComplexity: 'O(n)',
  },
  {
    id: 'TC058',
    name: 'divide_and_conquer_three_branches',
    code: 'function example(n) {\n  if (n <= 1) return 1;\n  return example(Math.floor(n / 2)) + example(Math.floor(n / 2)) + example(Math.floor(n / 2));\n}',
    expectedTimeComplexity: 'O(n^log2(3))',
    expectedSpaceComplexity: 'O(log n)',
  },
  {
    id: 'TC059',
    name: 'nested_loops_with_hash_lookup',
    code: 'function example(arr) {\n  const set = new Set(arr);\n  for (let i = 0; i < arr.length; i++) {\n    for (let j = i + 1; j < arr.length; j++) {\n      if (set.has(arr[i] + arr[j])) {\n        return true;\n      }\n    }\n  }\n  return false;\n}',
    expectedTimeComplexity: 'O(n^2) average',
    expectedSpaceComplexity: 'O(n)',
  },
  {
    id: 'TC060',
    name: 'complex_mixed_case',
    code: 'function example(arr) {\n  const map = new Map();\n  for (let i = 0; i < arr.length; i++) {\n    map.set(arr[i], i);\n  }\n  arr.sort((a, b) => a - b);\n  for (let i = 1; i < arr.length; i *= 2) {\n    for (let j = 0; j < arr.length; j++) {\n      if (map.has(arr[j])) {\n        continue;\n      }\n    }\n  }\n  return arr;\n}',
    expectedTimeComplexity: 'O(n log n)',
    expectedSpaceComplexity: 'O(n)',
  },
];
